### ISSUE TITLE
Fix some bugs

### ISSUE THREAD

**Issue by igorwastaken** [OnBeat-Project/OnBeat-Bot#18]
# Let's fix a ton of bugs!

## Infos
- Who can help?
    - Team people
    - Github contributors
    - You

# What bugs is here?
Nothing here

**Comment by rileyscool** [comment]
why put thing if no bugs

**Comment by igorwastaken** [comment]
> why put thing if no bugs

Yes there are bugs on both the site and the bot, I'm still looking
