### ISSUE TITLE
Create mobile support

### ISSUE THREAD

**Issue by igorwastaken** [OnBeat-Project/OnBeat-Bot#2]
Currently we have removed support for phones, let's create a new one!

![Dylan Stinks](https://user-images.githubusercontent.com/80823011/179379151-372b0c1e-ab24-4215-887f-a9b5a6c128fa.jpg)

**Comment by meyzatech** [comment]
Noted Sir!

**Comment by igorwastaken** [comment]
:tada: new commit! SEE!
